=== Danielfo684/LMSGI/XML/Ejemplo1/ejemplo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="biblioteca">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="libro" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titulo" type="xs:string"></xs:element>
							<xs:element name="autor" type="xs:string"></xs:element>
							<xs:element name="editorial" />
							<xs:element name="precio" type="tipo_precio" />
							<xs:element name="tapa" />
						</xs:sequence>
						<xs:attribute name="isbn" type="tipo_isbn" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:simpleType name="tipo_precio">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0" />
			<xs:maxExclusive value="120" />
			<xs:totalDigits value="5" />
			<xs:fractionDigits value="2"></xs:fractionDigits>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_tapa">
		<xs:restriction base="xs:string">
			<xs:enumeration value="blanda" />
			<xs:enumeration value="dura" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_editorial">
		<xs:restriction base="xs:string">
			<xs:minLength value="3" />
			<xs:maxLength value="50" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_isbn">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-z]){5}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Danielfo684/LMSGI/XML/Ejemplo1/ejemplo.xml
<?xml version="1.0" encoding="utf-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejemplo.xsd">
   <libro isbn="ebcde" >
    <titulo>Los pilares de la tierra</titulo>
    <autor>Ken Follet</autor>
    <editorial>patata</editorial>
    <precio>30.5</precio>
    <tapa>dura</tapa>
   </libro>


   <libro isbn="abcde">
    <titulo>Los pilares de la tierra</titulo>
    <autor>Ken Follet</autor>
    <editorial>patata</editorial>
    <precio>100.05</precio>
    <tapa>blanda</tapa>
   </libro>

</biblioteca>
